scriptencoding utf-8
colorscheme molokai

set termencoding=utf-8
set encoding=utf-8
set fileencodings=utf-8

set autoindent
set browsedir=buffer
set nocompatible
set incsearch
set number
set showmatch
set smartcase
set smartindent
set smarttab
set tabstop=4
"set termguicolors
set shiftwidth=4
set modeline
set shortmess+=I
set bs=indent,eol,start

call pathogen#infect()
